import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import Header from "@/components/header";
import SideNav from "@/components/side-nav";
// import HeaderMobile from "@/components/header-mobile";
import PageWrapper from "@/components/page-wrapper";
import MarginWidthWrapper from "@/components/margin-width-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white ${inter.className}`}>
        <div className="flex min-h-screen"> 
        <SideNav/>
          
          <div className="flex-1 flex flex-col pt-[60px] lg:pl-[288px]"> 
            
              <Header/>
              <PageWrapper>
                {children}
              </PageWrapper>
            
          </div>
        </div>
      </body>
    </html>
  );
}
